# Server properties
server:
  servlet:
    context-path: /docente-api
  port: 8080
# Spring properties
spring:
  # Dev is active by default. This value can be overwritten by java arg param 
  profiles:
    active: heroku2
  application:
    name: docente-api
