spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-184-73-169-163.compute-1.amazonaws.com:5432/da549s6alatudh
    driver-class-name: org.postgresql.Driver
    username: cdqnsrjjebaxxy
    password: 609438b5f5a79188129689a463fe21d9f61d102185507d7a31a8420042dc8daf

logging:
  level:
    root: INFO
  file: docente.log
